  - name: download latest stable redis
    yum: name=https://s3.amazonaws.com/runscope-packages/redis-3.2.10-2.el7.x86_64.rpm

  - name: create redis group
    group: name=redis state=present system=yes

  - name: create redis user
    user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

  - name: make sure that /mnt/redis/redis exists
    file: path=/mnt/redis/redis-{{ redis_port }} state=directory mode=0755 group=redis owner=redis

  - name: make sure redis.log file exists
    copy: src=templates/redis.log dest=/var/log/redis/redis-{{ redis_port }}.log owner=redis group=redis mode=0644

  - name: copy redis.conf file
    copy: src=templates/redis.conf dest=/etc/redis-{{ redis_port }}.conf group=redis owner=redis

  - name: copy custom template
    template: src=templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

  - name: copy redis-local script
    template: src=templates/redis-local.j2 dest=/usr/local/bin/redis-local mode=0755

  - name: ensure redis service is restarted
    service: name=redis state=restarted

